"""Initial models - users, farms, parcels, sowing, crop rotation, NDVI

Revision ID: 3fe49b8713dd
Revises:
Create Date: 2026-01-18 14:50:41.277255

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3fe49b8713dd"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_profiles",
        sa.Column(
            "user_id",
            sa.String(length=20),
            nullable=False,
            comment="Unique user ID (e.g., syn_user_001)",
        ),
        sa.Column(
            "full_name_masked",
            sa.String(length=50),
            nullable=False,
            comment="Masked name (e.g., [ŞƏXS_001])",
        ),
        sa.Column(
            "phone_hash", sa.String(length=64), nullable=True, comment="SHA256 hash of phone number"
        ),
        sa.Column(
            "region_code",
            sa.String(length=10),
            nullable=False,
            comment="ISO region code (e.g., AZ-ABS)",
        ),
        sa.Column(
            "experience_level",
            sa.String(length=20),
            nullable=False,
            comment="novice/intermediate/expert",
        ),
        sa.Column(
            "farming_years", sa.Integer(), nullable=False, comment="Years of farming experience"
        ),
        sa.Column(
            "education_level",
            sa.String(length=20),
            nullable=False,
            comment="primary/secondary/technical/university",
        ),
        sa.Column(
            "language_pref",
            sa.String(length=10),
            nullable=False,
            comment="Language code (az_AZ, ru_RU, en_US)",
        ),
        sa.Column(
            "preferred_units", sa.String(length=10), nullable=False, comment="metric or local"
        ),
        sa.Column(
            "receives_subsidies",
            sa.Boolean(),
            nullable=False,
            comment="Whether user receives government subsidies",
        ),
        sa.Column(
            "notification_pref", sa.String(length=10), nullable=False, comment="sms/app/both/none"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "farm_profiles",
        sa.Column(
            "farm_id",
            sa.String(length=20),
            nullable=False,
            comment="Unique farm ID (e.g., syn_farm_001a)",
        ),
        sa.Column("user_id", sa.String(length=20), nullable=False),
        sa.Column(
            "farm_name", sa.String(length=100), nullable=False, comment="Farm name in Azerbaijani"
        ),
        sa.Column(
            "farm_type",
            sa.String(length=20),
            nullable=False,
            comment="crop/livestock/orchard/mixed",
        ),
        sa.Column("region", sa.String(length=30), nullable=False, comment="Agricultural region"),
        sa.Column(
            "total_area_ha", sa.Float(), nullable=False, comment="Total farm area in hectares"
        ),
        sa.Column(
            "primary_activity",
            sa.String(length=50),
            nullable=False,
            comment="Primary crop/activity (e.g., wheat_cotton)",
        ),
        sa.Column(
            "is_primary",
            sa.Boolean(),
            nullable=False,
            comment="Whether this is the user's primary farm",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Whether the farm is currently active",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user_profiles.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("farm_id"),
    )
    op.create_index(op.f("ix_farm_profiles_user_id"), "farm_profiles", ["user_id"], unique=False)
    op.create_table(
        "parcels",
        sa.Column(
            "parcel_id",
            sa.String(length=20),
            nullable=False,
            comment="EKTIS parcel ID (e.g., AZ-ARN-1234)",
        ),
        sa.Column("farm_id", sa.String(length=20), nullable=False),
        sa.Column(
            "latitude",
            sa.Float(),
            nullable=False,
            comment="GPS latitude (38.0-42.0 for Azerbaijan)",
        ),
        sa.Column(
            "longitude",
            sa.Float(),
            nullable=False,
            comment="GPS longitude (44.0-51.0 for Azerbaijan)",
        ),
        sa.Column("area_hectares", sa.Float(), nullable=False, comment="Parcel area in hectares"),
        sa.Column(
            "soil_type", sa.String(length=20), nullable=False, comment="Soil type classification"
        ),
        sa.Column(
            "irrigation_type",
            sa.String(length=20),
            nullable=False,
            comment="Irrigation system type",
        ),
        sa.Column(
            "elevation_m", sa.Float(), nullable=True, comment="Elevation in meters above sea level"
        ),
        sa.Column("slope_percent", sa.Float(), nullable=True, comment="Land slope percentage"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["farm_id"], ["farm_profiles.farm_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("parcel_id"),
    )
    op.create_index(op.f("ix_parcels_farm_id"), "parcels", ["farm_id"], unique=False)
    op.create_table(
        "crop_rotation_logs",
        sa.Column("log_id", sa.String(length=30), nullable=False, comment="Unique log ID"),
        sa.Column("parcel_id", sa.String(length=20), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False, comment="Growing season year"),
        sa.Column(
            "crop", sa.String(length=50), nullable=False, comment="Crop grown (in Azerbaijani)"
        ),
        sa.Column(
            "yield_tons_per_ha", sa.Float(), nullable=True, comment="Yield in tons per hectare"
        ),
        sa.Column("total_yield_tons", sa.Float(), nullable=True, comment="Total yield in tons"),
        sa.Column(
            "quality_grade", sa.String(length=10), nullable=True, comment="Quality grade (A, B, C)"
        ),
        sa.Column(
            "notes",
            sa.String(length=500),
            nullable=True,
            comment="Additional notes about the season",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parcel_id"], ["parcels.parcel_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("log_id"),
    )
    op.create_index(
        op.f("ix_crop_rotation_logs_parcel_id"), "crop_rotation_logs", ["parcel_id"], unique=False
    )
    op.create_table(
        "ndvi_readings",
        sa.Column("reading_id", sa.String(length=30), nullable=False, comment="Unique reading ID"),
        sa.Column("parcel_id", sa.String(length=20), nullable=False),
        sa.Column("reading_date", sa.Date(), nullable=False, comment="Date of satellite reading"),
        sa.Column("ndvi_value", sa.Float(), nullable=False, comment="NDVI value (-1.0 to 1.0)"),
        sa.Column(
            "health_status",
            sa.String(length=20),
            nullable=False,
            comment="Derived health classification",
        ),
        sa.Column("evi_value", sa.Float(), nullable=True, comment="Enhanced Vegetation Index"),
        sa.Column(
            "soil_moisture_index", sa.Float(), nullable=True, comment="Soil moisture index (0-1)"
        ),
        sa.Column(
            "cloud_cover_percent",
            sa.Float(),
            nullable=True,
            comment="Cloud cover percentage (0-100)",
        ),
        sa.Column(
            "data_source",
            sa.String(length=50),
            nullable=False,
            comment="Data source (synthetic, Sentinel-2, etc.)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parcel_id"], ["parcels.parcel_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("reading_id"),
    )
    op.create_index(
        op.f("ix_ndvi_readings_parcel_id"), "ndvi_readings", ["parcel_id"], unique=False
    )
    op.create_index(
        op.f("ix_ndvi_readings_reading_date"), "ndvi_readings", ["reading_date"], unique=False
    )
    op.create_table(
        "sowing_declarations",
        sa.Column(
            "declaration_id",
            sa.String(length=30),
            nullable=False,
            comment="Declaration ID (e.g., DECL-2026-123456)",
        ),
        sa.Column("parcel_id", sa.String(length=20), nullable=False),
        sa.Column(
            "crop_type", sa.String(length=30), nullable=False, comment="Type of crop planted"
        ),
        sa.Column(
            "crop_variety",
            sa.String(length=50),
            nullable=True,
            comment="Specific variety (e.g., 'Garagylchyg' wheat)",
        ),
        sa.Column("sowing_date", sa.Date(), nullable=False, comment="Date of sowing"),
        sa.Column(
            "expected_harvest_date", sa.Date(), nullable=True, comment="Expected harvest date"
        ),
        sa.Column(
            "actual_harvest_date",
            sa.Date(),
            nullable=True,
            comment="Actual harvest date (when completed)",
        ),
        sa.Column("status", sa.String(length=20), nullable=False, comment="Declaration status"),
        sa.Column(
            "expected_yield_tons", sa.Float(), nullable=True, comment="Expected yield in tons"
        ),
        sa.Column(
            "actual_yield_tons",
            sa.Float(),
            nullable=True,
            comment="Actual yield in tons (after harvest)",
        ),
        sa.Column("season_year", sa.Integer(), nullable=False, comment="Growing season year"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parcel_id"], ["parcels.parcel_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("declaration_id"),
    )
    op.create_index(
        op.f("ix_sowing_declarations_parcel_id"), "sowing_declarations", ["parcel_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sowing_declarations_parcel_id"), table_name="sowing_declarations")
    op.drop_table("sowing_declarations")
    op.drop_index(op.f("ix_ndvi_readings_reading_date"), table_name="ndvi_readings")
    op.drop_index(op.f("ix_ndvi_readings_parcel_id"), table_name="ndvi_readings")
    op.drop_table("ndvi_readings")
    op.drop_index(op.f("ix_crop_rotation_logs_parcel_id"), table_name="crop_rotation_logs")
    op.drop_table("crop_rotation_logs")
    op.drop_index(op.f("ix_parcels_farm_id"), table_name="parcels")
    op.drop_table("parcels")
    op.drop_index(op.f("ix_farm_profiles_user_id"), table_name="farm_profiles")
    op.drop_table("farm_profiles")
    op.drop_table("user_profiles")
    # ### end Alembic commands ###
