#!/usr/bin/env python
"""🌾 ALİM - LangGraph Checkpoint Table Setup Script.

This script initializes the LangGraph checkpoint tables in PostgreSQL.
Tables are auto-generated by LangGraph when the checkpointer is first used.

Usage:
    python scripts/setup_langgraph_checkpoint_tables.py

Tables Created:
    - checkpoints (main state storage)
    - checkpoint_writes (incremental state writes)
    - checkpoint_blobs (large binary state data)
    - checkpoint_migrations (schema versioning)

Best Practice: LangGraph auto-manages these tables.
This script just triggers the initial setup.
"""
# ruff: noqa: E402 - imports must come after sys.path manipulation

import asyncio
import os
import sys

# Add src to path for imports
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

# CRITICAL: On Windows, psycopg requires SelectorEventLoop, not ProactorEventLoop
# This must be set BEFORE any async code runs
if sys.platform == "win32":
    # Force SelectorEventLoop for psycopg compatibility
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

from alim.agent.memory import get_checkpointer_async, reset_checkpointer


async def setup_langgraph_tables():
    """Initialize LangGraph checkpoint tables in PostgreSQL.

    This triggers the checkpointer.setup() which creates:
    - checkpoints table
    - checkpoint_writes table
    - checkpoint_blobs table
    - checkpoint_migrations table (for schema versioning)
    """
    print("═" * 60)
    print("🌾 ALİM - LangGraph Checkpoint Table Setup")
    print("═" * 60)

    # Get database URL from environment or use default
    postgres_url = os.getenv(
        "DATABASE_URL", "postgresql+asyncpg://alim:alim_dev_password@localhost:5433/alim"
    )

    # Convert asyncpg URL to standard psycopg format for checkpointer
    if "+asyncpg" in postgres_url:
        psycopg_url = postgres_url.replace("+asyncpg", "")
    else:
        psycopg_url = postgres_url

    print(f"\n📍 Target Database: {psycopg_url[:50]}...")

    # Reset singleton to force fresh initialization
    reset_checkpointer()

    print("\n🔄 Initializing checkpointer...")

    try:
        # Force PostgreSQL backend (not Redis or Memory)
        # The checkpointer.setup() is called internally, creating the tables
        _ = await get_checkpointer_async(
            postgres_url=postgres_url,
            backend="postgres",  # Explicitly use PostgreSQL
            use_singleton=False,  # Don't cache, we just want to setup
        )

        # The setup() call inside get_checkpointer_async already created tables
        print("\n✅ LangGraph checkpoint tables created successfully!")
        print("\n📊 Tables should now exist:")
        print("   • checkpoints")
        print("   • checkpoint_writes")
        print("   • checkpoint_blobs")
        print("   • checkpoint_migrations")

        return True

    except Exception as e:
        print(f"\n❌ Failed to setup LangGraph tables: {e}")
        print("\n💡 Possible causes:")
        print("   1. PostgreSQL not running (run Docker Start task)")
        print("   2. langgraph-checkpoint-postgres not installed")
        print("   3. Database connection failed")
        print("   4. Windows ProactorEventLoop issue (try WSL or Linux)")

        # Check if it's the Windows event loop issue
        if "ProactorEventLoop" in str(e):
            print("\n⚠️  Windows Event Loop Issue Detected!")
            print("   LangGraph's psycopg requires SelectorEventLoop.")
            print("   On Windows, this may not work directly.")
            print("   Consider using Redis checkpointer instead.")

        return False


async def verify_tables():
    """Verify that LangGraph tables exist in the database."""
    print("\n" + "═" * 60)
    print("🔍 Verifying LangGraph Tables")
    print("═" * 60)

    try:
        import asyncpg

        # Connect directly to PostgreSQL
        conn = await asyncpg.connect(
            host="localhost",
            port=5433,
            database="alim",
            user="alim",
            password="alim_dev_password",
        )

        # Query for LangGraph-related tables
        tables = await conn.fetch(
            """
            SELECT table_name
            FROM information_schema.tables
            WHERE table_schema = 'public'
            AND (
                table_name LIKE 'checkpoint%'
                OR table_name LIKE 'langgraph%'
            )
            ORDER BY table_name
        """
        )

        await conn.close()

        if tables:
            print("\n✅ LangGraph tables found:")
            for row in tables:
                print(f"   • {row['table_name']}")
            return True
        else:
            print("\n⚠️  No LangGraph checkpoint tables found!")
            print("   Tables may be created on first agent invocation.")
            return False

    except ImportError:
        print("\n⚠️  asyncpg not available for direct verification")
        print("   Run: poetry install")
        return None
    except Exception as e:
        print(f"\n❌ Verification failed: {e}")
        return False


async def main():
    """Main entry point."""
    # First verify what exists
    tables_exist = await verify_tables()

    if tables_exist:
        print("\n✅ LangGraph tables already exist! No action needed.")
        return

    # Try to create tables
    print("\n" + "═" * 60)
    print("🛠️  Attempting to Create LangGraph Tables")
    print("═" * 60)

    success = await setup_langgraph_tables()

    if success:
        # Verify again
        await verify_tables()
    else:
        print("\n💡 Alternative: Run the demo-ui and start a conversation.")
        print("   Tables are created automatically on first use.")


if __name__ == "__main__":
    asyncio.run(main())
